### ISSUE TITLE
Animations from SnM and BLOWJOBZ libraries not working

### ISSUE THREAD

**Issue by ddanyk** [openmultiplayer/open.mp#674]
When I try to apply animation to an actor or a player from BLOWJOBZ or SnM libraries, nothing happens.

Issue on windows and linux version RC2

Example:
```
ApplyActorAnimation(actorid, "BLOWJOBZ", "BJ_Stand_Start_W", 4.1, false, false, false, true,0);
ApplyAnimation(playerid, "BLOWJOBZ", "BJ_Stand_Start_P", 4.1, false, false, false, true, 0,SYNC_ALL);
ApplyAnimation(playerid,"SnM","SnM_Cane_W",4.1,false,false,true,false,0,SYNC_ALL);
```
Video: https://www.youtube.com/watch?v=ILM6TPeOdGs

**Comment by AmyrAhmady** [comment]
already fixed in next build, you can download a fixed version from here and use it till official release
https://github.com/openmultiplayer/open.mp/actions/runs/5245434673

**Comment by ddanyk** [comment]
Sorry but none of the builds I found have these libraries fixed. Animations are still not loading.

**Comment by AmyrAhmady** [comment]
Sorry, this seems to be turned into a config option now but disabled by default, it will be set to true by default in next build, as of now, in your config.json you can set `use_all_animations` in `game` to true

**Comment by AmyrAhmady** [comment]
Must be added to #671

**Comment by AmyrAhmady** [comment]
Try this one, should be fixed:
https://github.com/openmultiplayer/open.mp/actions/runs/5298835448
